-- Users and authentication tables
CREATE TABLE Users (
  user_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE Sellers (
  seller_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR,
  address VARCHAR
);

CREATE TABLE Accounts (
  account_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER,
  seller_id INTEGER,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR,
  name VARCHAR,
  address VARCHAR,
  balance DECIMAL(12, 2)
);

-- Product and category tables
CREATE TABLE Categories (
  category_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR,
  description TEXT,
  parent_id INTEGER
);

CREATE TABLE Products (
  product_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR UNIQUE,
  description TEXT,
  image VARCHAR,
  category_id INTEGER,
  creator_id INTEGER
);

CREATE TABLE Product_reviews (
  product_review_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER,
  product_id INTEGER,
  review_text TEXT,
  rating INTEGER,
  updated_at TIMESTAMP,
  upvote_count INTEGER DEFAULT 0
);

-- Create a table to track which users have upvoted which reviews
CREATE TABLE review_upvotes (
    id SERIAL PRIMARY KEY,
    review_id INTEGER NOT NULL REFERENCES product_reviews(product_review_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE(review_id, user_id)
);

CREATE TABLE Seller_reviews (
  seller_review_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  seller_id INTEGER,
  user_id INTEGER,
  review_text TEXT,
  rating INTEGER,
  updated_at TIMESTAMP
);

-- Inventory management
CREATE TABLE Inventory (
  item_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  seller_id INTEGER,
  product_id INTEGER,
  price DECIMAL(12, 2),
  quantity INTEGER,
  created_at TIMESTAMP,
  publish_status TEXT DEFAULT 'published',   -- add：'published' by default --jiechen
  low_stock_quantity INTEGER DEFAULT 50      -- add：50 by default --jiechen
);

-- Cart and wishlist
CREATE TABLE Cart (
  cart_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER,
  updated_at TIMESTAMP
);

CREATE TABLE Cart_items (
  cart_item_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cart_id INTEGER,
  product_id INTEGER,
  seller_id INTEGER,
  quantity INTEGER,
  unit_price DECIMAL(12, 2),
  total_price DECIMAL(12, 2)
);

-- Purchase and transaction tables
CREATE TABLE Purchases (
  purchase_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER,
  total_amount DECIMAL(12, 2),
  total_items INTEGER,
  status VARCHAR,
  updated_at TIMESTAMP
);

CREATE TABLE Purchase_items (
  purchase_item_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  purchase_id INTEGER,
  product_id INTEGER,
  seller_id INTEGER,
  quantity INTEGER,
  unit_price DECIMAL(12, 2),
  total_price DECIMAL(12, 2),
  fulfillment_status VARCHAR,
  updated_at TIMESTAMP
);

CREATE TABLE Seller_purchases (
  seller_purchase_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER,
  seller_id INTEGER,
  purchase_id INTEGER,
  total_amount DECIMAL(12, 2),
  total_items INTEGER,
  status VARCHAR,
  updated_at TIMESTAMP
);

CREATE TABLE Seller_purchase_items (
  seller_purchase_item_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  seller_purchase_id INTEGER,
  product_id INTEGER,
  quantity INTEGER,
  unit_price DECIMAL(12, 2),
  total_price DECIMAL(12, 2),
  fulfillment_status VARCHAR,
  updated_at TIMESTAMP
);

CREATE TABLE Account_transactions (
  account_transaction_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  purchase_id INTEGER,
  account_id INTEGER,
  amount DECIMAL(12, 2),
  transaction_type VARCHAR,
  created_at TIMESTAMP
);

CREATE TABLE Coupons (
  coupon_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code VARCHAR UNIQUE NOT NULL,
  discount_percent DECIMAL(5, 2),
  valid_from TIMESTAMP,
  valid_until TIMESTAMP,
  is_active BOOLEAN
);


CREATE TABLE Saved_items (
  saved_item_id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  seller_id INTEGER,
  added_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE BalanceHistory (
  id SERIAL PRIMARY KEY,
  account_id INTEGER REFERENCES Accounts(account_id),
  amount DECIMAL(12, 2) NOT NULL,
  new_balance DECIMAL(12, 2) NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

